version: "3.8"
services:
    urlprompt:
        image: ghcr.io/splunk/urlprompt
        environment:
        - DEBUG=false
        - DATABASE_URL=sqlite:////app/db/db.sqlite3
        - SECRET_KEY=changemepls
        - URLPROMPT_ADMIN_USER=urladmin
        - URLPROMPT_ADMIN_PASS=changeme
        volumes:
        - urlprompt-db:/app/db/:rw
        build: .
        ports: 
        - "5000:5000"
volumes:
    urlprompt-db: