version: "3.8"
services:
    urlprompt:
        image: ghcr.io/splunk/urlprompt
        environment:
        - DEBUG=false
        - DATABASE_URL=sqlite:////app/db/db.sqlite3
        - SECRET_KEY=changemepls
        volumes:
        - ./db/:/app/db/
        build: .
        ports: 
        - "5000:5000"
