site_name: URL Prompts for Phantom


theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.tabs
  icon:
    logo: material/link-variant

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - URLP Server:
    - urlp/index.md
    - urlp/deployment.md
    - urlp/prompt_schema.md
    - urlp/api_documentation.md
  - Phantom App:
    - app/index.md
