site_name: URL Prompts for Phantom
repo_url: https://github.com/splunk/urlprompt
repo_name: splunk/urlprompt
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.tabs
  icon:
    logo: material/link-variant
    repo: fontawesome/brands/github

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - URLP Server:
    - urlp/index.md
    - urlp/deployment.md
    - urlp/runbook.md
    - urlp/prompt_schema.md
    - urlp/api_documentation.md
  - Phantom App:
    - app/index.md

plugins:
  - git-revision-date
