site_name: urlprompt
repo_url: https://github.com/splunk/urlprompt
repo_name: splunk/urlprompt
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    primary: green
    scheme: slate
  icon:
    logo: material/link-variant
    repo: fontawesome/brands/github
  favicon: assets/favicon.png

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - index.md
  - Server Setup:
    - urlp/index.md
    - urlp/deployment.md
    - urlp/runbook.md
    - urlp/api_documentation.md
  - SOAR Setup:
    - soar/index.md
    - soar/playbooks.md
    - soar/json_prompts.md

plugins:
  - git-revision-date
